name: gen
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  lottie: ^2.6.8
  envied: ^0.3.0+3
  equatable: ^2.0.5
  flutter_gen: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.4.0

flutter_gen:
  output: lib/src/asset/
  integrations:
    flutter_svg: true
    lottie: true 

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/