name: pureblog
description: "A blog project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies
  kartal: ^3.4.4
  vexana: ^3.5.4
  flutter_riverpod: ^2.4.4
  easy_localization: ^3.0.3
  google_fonts: ^6.2.1
  auto_route: ^7.9.0

  # Utility
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  get_it: ^7.6.7

  # Modules
  core:
    path: module/core/  
  common: 
    path: module/common/
  widget:
    path: module/widget/
  gen:
    path: module/gen/
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Core Dev Dependencies
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  device_preview: ^1.1.0
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "module/gen/assets/images/icon.png"
  min_sdk_version: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - module/gen/assets/translations/